name: Copy Secrets
on:
  workflow_dispatch:
    inputs:
      source:
        type: environment
        description: 'Source environment'
        required: true
      destination:
        type: environment
        description: 'Destination environment'
        required: true

permissions:
  contents: write
  id-token: write

defaults:
  run:
    shell: pwsh

jobs:
  copy_secrets:
    environment: ${{ inputs.source }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Copy secrets
        shell: pwsh
        run: |
          $secrets_source = ('${{ toJson(secrets) }}' | ConvertFrom-Json -AsHashTable)

          foreach($s in $secrets_source.GetEnumerator()) {
            gh secret set $($s.Name) -b $($s.Value) --env ${{ inputs.destination }}
          }