name: Copy Secrets
on:
  workflow_dispatch:
    inputs:
      source:
        type: environment
        description: 'Source environment'
        required: true
      destination:
        type: environment
        description: 'Destination environment'
        required: true

permissions:
  contents: write
  id-token: write

defaults:
  run:
    shell: pwsh

jobs:
  copy_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Copy secrets
        shell: pwsh
        run: |
          $secrets_source = ('${{ toJson(secrets) }}') # | ConvertFrom-Json -AsHashTable)

          $secrets_source > ./secrets.json

      - name: Upload secrets
        uses: actions/upload-artifact@v2
        with:
          path: ./secrets.json